name: Deploy to Alibaba Cloud ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: davidzhu/django-test1
  IMAGE_TAG: v0.1.9
  REGION: cn-shanghai
  ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY }}
  ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_SECRET_KEY }}
  ECS_CLUSTER_ID: 47.100.18.252
  ECS_TASK_NAME: <your-ecs-task-name>

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        registry: registry.${{ env.REGION }}.aliyuncs.com
        username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}

    #- name: Install Python dependencies
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get -y install python3-pip
    #    pip3 install -r requirements.txt

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: registry.${{ env.REGION }}.aliyuncs.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      env:
        DOCKER_USERNAME: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}

    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair,ssh 连接密钥
        SSH_PRIVATE_KEY: ${{ env.ACCESS_KEY_SECRET }}
        # Remote host
        REMOTE_HOST: ${{ env.ECS_CLUSTER_ID }}
        # Remote user
        REMOTE_USER: ${{ env.ACCESS_KEY_ID }}
        # Remote port
        # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
        # SOURCE: "./dist" # optional, default is 
        # Target directory,把当前的项目代码目标拷贝到Target目录
        TARGET:  "/opt/djangotest1"
        # Arguments to pass to rsync
        run: |
          echo 'djangotest' > test1.txt
        
        
